#include "stm32f1xx_hal.h"
#include "fonts.h"

/**
 * This Library is written and optimized by Olivier Van den Eede(4ilo) in 2016
 * for Stm32 Uc and HAL-i2c lib's.
 *
 * To use this library with ssd1306 oled display you will need to customize the defines below.
 *
 * This library uses 2 extra files (fonts.c/h).
 * In this files are 3 different fonts you can use:
 * 		- Font_7x10
 * 		- Font_11x18
 * 		- Font_16x26
 *
 */

#ifndef ssd1306
#define ssd1306

void UpdateGridBox(char* str, uint8_t lcd_id);

// I2c port as defined in main generated by CubeMx
#define SSD1306_I2C_PORT		hi2c1
// I2c address
#define SSD1306_I2C_ADDR1        0x78
#define SSD1306_I2C_ADDR2        0x7A
// SSD1306 width in pixels
#define SSD1306_WIDTH           128
// SSD1306 LCD height in pixels
#define SSD1306_HEIGHT          64
#define SSD1306_TIMEOUT			20

#define MAIN_LCD				1
#define SECOND_LCD				0

#define MAX_STRING_LEN 20
uint8_t grid_data[4][15];
uint8_t grid_y;
uint8_t stringGridBox[2][4*MAX_STRING_LEN];
#define LOGGER_STRING "Logger:"
//
//  Enumeration for screen colors
//
typedef enum {
	Black = 0x00, // Black color, no pixel
	White = 0x01  //Pixel is set. Color depends on LCD
} SSD1306_COLOR;

//
//  Struct to store transformations
//
typedef struct {
	uint16_t CurrentX;
	uint16_t CurrentY;
	uint8_t Inverted;
	uint8_t Initialized;
} SSD1306_t;

//	Definition of the i2c port in main
extern I2C_HandleTypeDef SSD1306_I2C_PORT;

//
//  Function definitions
//
uint8_t ssd1306_Init(uint8_t lcd_id);
void ssd1306_Fill(SSD1306_COLOR color,uint8_t lcd_id);
void ssd1306_UpdateScreen(uint8_t lcd_id);
void ssd1306_DrawPixel(uint8_t x, uint8_t y, SSD1306_COLOR color,uint8_t lcd_id);
uint8_t ssd1306_WriteChar(uint8_t ch, FontDef Font, SSD1306_COLOR color,uint8_t lcd_id);
uint8_t ssd1306_WriteString(char* str, FontDef Font, SSD1306_COLOR color,uint8_t lcd_id);
void ssd1306_SetCursor(uint8_t x, uint8_t y,uint8_t lcd_id);
void ShowClapsTitle(uint8_t lcd_id);
void ssd1306_WriteCommand(uint8_t cmd, uint8_t id);
void start_title(uint8_t lcd_id);
void ShowUartMonitor(uint8_t lcd_id);
#endif
